sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/770bcef2174e57ba7511
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
  email: false
node_js:
  - '6'
before_script:
  - npm prune
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
